syntax = "proto2";

package com.repldriven.queenswood.schemas.balances;

import "record_metadata_options.proto";
import "schemas/account-product-type/account-product-type.proto";
import "schemas/balances/types.proto";

option java_outer_classname = "AccountBalanceProto";

// One bucket of an account's balance.
message AccountBalance {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string bank_id = 1;
  required string account_id = 2;
  required BalanceType balance_type = 3;
  required BalanceStatus balance_status = 4;

  required com.repldriven.queenswood.schemas.account_product_type.AccountProductType product_type = 5;
  required int64 credit = 6;
  required int64 debit = 7;

  required int64 created_at = 101;
}
