system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  policies: !include system/policy-test.yml
  webhook:
    event-processor-impl: !system/component
      system/component-kind: webhook/event-processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde

