syntax = "proto2";

package com.repldriven.queenswood.schemas.policies;

import "schemas/amounts/amount.proto";
import "schemas/balances/types.proto";
import "schemas/banks/bank.proto";
import "schemas/cash-accounts/types.proto";
import "schemas/party/party.proto";
import "schemas/policies/capability.proto";
import "schemas/policies/types.proto";
import "schemas/schemes/scheme.proto";
import "schemas/transactions/transaction.proto";
import "schemas/types/product-type.proto";

option java_outer_classname = "LimitProto";

enum TimeWindow {
  TIME_WINDOW_UNKNOWN = 0;
  TIME_WINDOW_INSTANT = 1;
  TIME_WINDOW_DAILY = 2;
  TIME_WINDOW_WEEKLY = 3;
  TIME_WINDOW_MONTHLY = 4;
  TIME_WINDOW_ROLLING = 5;
}

message AmountAggregate {
  required com.repldriven.queenswood.schemas.amounts.Amount value = 1;
  required TimeWindow window = 2;
  optional int64 rolling_window_ms = 3;
}

message CountAggregate {
  optional int64 value = 1;
  required TimeWindow window = 2;
  optional int64 rolling_window_ms = 3;
}

message Aggregate {
  oneof kind {
    AmountAggregate amount = 1;
    CountAggregate count = 2;
  }
}

message MaxBound {
  required Aggregate aggregate = 1;
}

message MinBound {
  required Aggregate aggregate = 1;
}

message RangeBound {
  required Aggregate min = 1;
  required Aggregate max = 2;
}

message Bound {
  oneof kind {
    MaxBound max = 1;
    MinBound min = 2;
    RangeBound range = 3;
  }
}

enum LimitAllow {
  LIMIT_ALLOW_UNKNOWN = 0;
  LIMIT_ALLOW_IMPROVING = 1;
}

message ActualBalance {
  required com.repldriven.queenswood.schemas.balances.BalanceType type = 1;
  required com.repldriven.queenswood.schemas.balances.BalanceStatus status = 2;
}

message ComputedBalance {
  required string name = 1;
}

message BalanceLimitFilter {
  oneof kind {
    ActualBalance actual = 1;
    ComputedBalance computed = 2;
  }
  optional com.repldriven.queenswood.schemas.transactions.TransactionType transaction_type = 3;
}

message BalanceLimit {
  repeated BalanceLimitFilter filters = 1;
}

message BankLimitFilter {
  optional com.repldriven.queenswood.schemas.banks.BankStatus status = 2;
}

message BankLimit {
  repeated BankLimitFilter filters = 1;
}

message CashAccountLimitFilter {
  optional com.repldriven.queenswood.schemas.types.ProductType product_type = 1;
  optional com.repldriven.queenswood.schemas.cash_accounts.AccountType account_type = 2;
  optional string currency = 3;
}

message CashAccountLimit {
  repeated CashAccountLimitFilter filters = 1;
}

enum CashAccountMigrationAction {
  CASH_ACCOUNT_MIGRATION_ACTION_UNKNOWN = 0;
  CASH_ACCOUNT_MIGRATION_ACTION_COMMIT = 1;
  CASH_ACCOUNT_MIGRATION_ACTION_PREVIEW = 2;
}

message CashAccountMigrationLimitFilter {
  optional CashAccountMigrationAction action = 1;
}

message CashAccountMigrationLimit {
  repeated CashAccountMigrationLimitFilter filters = 1;
}

message CashAccountProductLimitFilter {
  optional com.repldriven.queenswood.schemas.types.ProductType product_type = 1;
}

message CashAccountProductLimit {
  repeated CashAccountProductLimitFilter filters = 1;
}

message IdvLimit {}

message InboundPaymentLimitFilter {
  optional com.repldriven.queenswood.schemas.schemes.SchemeType scheme = 1;
}

message InboundPaymentLimit {
  repeated InboundPaymentLimitFilter filters = 1;
}

message InterestLimitFilter {
  optional InterestAction action = 1;
}

message InterestLimit {
  repeated InterestLimitFilter filters = 1;
}

message InternalPaymentLimit {}

message OutboundPaymentLimitFilter {
  optional com.repldriven.queenswood.schemas.schemes.SchemeType scheme = 1;
}

message OutboundPaymentLimit {
  repeated OutboundPaymentLimitFilter filters = 1;
}

message PartyLimitFilter {
  optional com.repldriven.queenswood.schemas.party.PartyType type = 1;
  optional com.repldriven.queenswood.schemas.party.PartyStatus status = 2;
}

message PartyLimit {
  repeated PartyLimitFilter filters = 1;
}

message PayeeCheckLimit {}

message PolicyLimitFilter {
  optional PolicyCategory category = 1;
}

message PolicyLimit {
  repeated PolicyLimitFilter filters = 1;
}

message TransactionLimit {}

message WebhookEndpointLimit {}

message Limit {
  required Bound bound = 1;
  optional string reason = 2;
  optional LimitAllow allow = 3;

  oneof kind {
    BalanceLimit balance = 11;
    BankLimit bank = 12;
    CashAccountLimit cash_account = 13;
    CashAccountMigrationLimit cash_account_migration = 14;
    CashAccountProductLimit cash_account_product = 15;
    IdvLimit idv = 16;
    InboundPaymentLimit inbound_payment = 17;
    InterestLimit interest = 18;
    InternalPaymentLimit internal_payment = 19;
    OutboundPaymentLimit outbound_payment = 20;
    PartyLimit party = 21;
    PayeeCheckLimit payee_check = 22;
    PolicyLimit policy = 23;
    TransactionLimit transaction = 24;
    WebhookEndpointLimit webhook_endpoint = 25;
  }
}
