syntax = "proto2";

package com.repldriven.queenswood.schemas.policies;

import "record_metadata_options.proto";
import "schemas/actor/actor.proto";
import "schemas/policies/capability.proto";
import "schemas/policies/limit.proto";
import "schemas/policies/types.proto";

option java_outer_classname = "PolicyProto";

enum PolicyStatus {
  POLICY_STATUS_UNKNOWN = 0;
  POLICY_STATUS_ACTIVE = 1;
  POLICY_STATUS_DISABLED = 2;
  POLICY_STATUS_ARCHIVED = 3;
}

// A set of capabilities and limits a request is evaluated against.
message Policy {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string policy_id = 1 [(com.apple.foundationdb.record.field).primary_key = true]; // pol.<ulid>

  required string name = 2;
  required PolicyStatus status = 3;
  required PolicyCategory category = 4;
  optional string description = 5;
  repeated Capability capabilities = 6;
  repeated Limit limits = 7;
  map<string, string> labels = 8;

  optional int64 archived_at = 51;
  optional com.repldriven.queenswood.schemas.actor.Actor archived_by = 52;

  required int64 created_at = 101;
  optional int64 updated_at = 103;
}
