syntax = "proto2";

package com.repldriven.queenswood.schemas.policies;

import "record_metadata_options.proto";
import "schemas/actor/actor.proto";
import "schemas/cash-accounts/types.proto";
import "schemas/schemes/scheme.proto";

option java_outer_classname = "PolicyBindingProto";

message AccountTarget {
  oneof selector {
    string account_id = 1;
    com.repldriven.queenswood.schemas.cash_accounts.AccountType account_type = 2;
  }
}

message BankTarget {
  required string bank_id = 1;
}

message PartyTarget {
  optional string party_id = 1;
}

message PlatformTarget {}

message SchemeTarget {
  required com.repldriven.queenswood.schemas.schemes.SchemeType scheme = 1;
  optional string bank_id = 2;
}

message Target {
  oneof kind {
    AccountTarget account = 1;
    BankTarget bank = 2;
    PartyTarget party = 3;
    PlatformTarget platform = 4;
    SchemeTarget scheme = 5;
  }
}

// A policy applied to a target.
message PolicyBinding {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string binding_id = 1 [(com.apple.foundationdb.record.field).primary_key = true]; // bnd.<ulid>
  required string policy_id = 2;
  required Target target = 3;
  optional string reason = 4;

  required int64 created_at = 101;
  required com.repldriven.queenswood.schemas.actor.Actor created_by = 102;
}
