system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  payment-provider: !include system/payment-provider.yml
  server: !include modulr-adapter/server-test.yml
  modulr-adapter: !include modulr-adapter/modulr-adapter-test.yml
