system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  message-bus: !include form3-relay/message-bus-test.yml
  relay-handler:
    handler: !system/component
      system/component-kind: changelog-relay/envelope-handler
      bus: !system/ref message-bus.bus
      store-name: form3-outbox
      event-channel: !keyword schemes-payments-event
      event-channels: !include system/payment-account-event-channels.yml
