system:
  telemetry: !include system/telemetry.yml
  scheme-simulator: !include system/scheme-simulator.yml
  modulr-simulator-server: !include system/modulr-simulator-server.yml
  form3-simulator-server: !include system/form3-simulator-server.yml
  clearbank-simulator-server: !include system/clearbank-simulator-server.yml
  zyphe-simulator-server: !include system/zyphe-simulator-server.yml
  onfido-simulator-server: !include system/onfido-simulator-server.yml
  uk-companies-house-simulator-server: !include system/uk-companies-house-simulator-server.yml
