system:
  avro: !include system/avro.yml
  banks: !include system/bank.yml
  banks-dispatcher: !include system/bank-dispatcher.yml
  cash-account-product-templates: !include system/cash-account-product-templates.yml
  cash-accounts: !include system/cash-account.yml
  cash-accounts-dispatcher: !include system/cash-account-dispatcher.yml
  cash-accounts-relay: !include system/cash-account-relay.yml
  companies-dispatcher: !include system/company-dispatcher.yml
  email: !include system/email.yml
  fdb: !include system/fdb-test.yml
  idv: !include system/idv.yml
  idvs-relay: !include system/idv-relay.yml
  idvs-dispatcher: !include system/idv-dispatcher.yml
  invitations-relay: !include system/invitation-relay.yml
  kafka: !include system/kafka-all-test.yml
  keycloak: !include system/keycloak.yml
  keycloak-container: !include system/keycloak-container-test.yml
  memberships: !include system/membership.yml
  memberships-dispatcher: !include system/membership-dispatcher.yml
  message-bus: !include system/message-bus-test.yml
  modulr-adapter: !include system/modulr-adapter.yml
  modulr-adapter-relay: !include system/modulr-adapter-relay.yml
  modulr-adapter-server: !include system/modulr-adapter-server.yml
  modulr-simulator-server: !include system/modulr-simulator-server.yml
  parties: !include test-api-scenarios/party-test.yml
  parties-relay: !include system/party-relay.yml
  payee-checks: !include system/payee-check-test.yml
  payments: !include system/payment.yml
  payments-dispatcher: !include system/payment-dispatcher.yml
  payment-sweep: !include system/payment-outbound-sweep.yml
  policies: !include system/policy-test.yml
  scenario-policies: !include test-api-scenarios/policy-test.yml
  server: !include test-api-scenarios/server-test.yml
  smtp: !include system/smtp-test.yml
  telemetry: !include system/telemetry.yml
  test-api-scenarios:
    span-dump: !system/component
      system/component-kind: test-api-scenarios/span-dump
      path: !env QW_SPAN_DUMP
  transactions: !include system/transaction.yml
  transactions-dispatcher: !include system/transaction-dispatcher.yml
  transactions-relay: !include system/transaction-relay.yml
  uk-companies-house-adapter: !include system/uk-companies-house-adapter.yml
  uk-companies-house-simulator-server: !include system/uk-companies-house-simulator-server.yml
  zyphe-adapter: !include system/zyphe-adapter.yml
  zyphe-adapter-relay: !include system/zyphe-adapter-relay.yml
  zyphe-adapter-server: !include system/zyphe-adapter-server.yml
  zyphe-simulator-server: !include system/zyphe-simulator-server.yml
