system:
  avro: !include system/avro.yml
  banks: !include system/bank.yml
  banks-dispatcher: !include system/bank-dispatcher.yml
  cash-account-product-templates: !include system/cash-account-product-templates.yml
  cash-accounts: !include system/cash-account.yml
  cash-accounts-dispatcher: !include system/cash-account-dispatcher.yml
  cash-accounts-relay: !include system/cash-account-relay.yml
  clearbank-adapter: !include system/clearbank-adapter.yml
  clearbank-adapter-relay: !include system/clearbank-adapter-relay.yml
  clearbank-adapter-server: !include system/clearbank-adapter-server.yml
  clearbank-simulator-server: !include system/clearbank-simulator-server.yml
  companies-dispatcher: !include system/company-dispatcher.yml
  fdb: !include system/fdb-test.yml
  idv: !include system/idv.yml
  idvs-relay: !include system/idv-relay.yml
  interest: !include system/interest.yml
  interest-dispatcher: !include system/interest-dispatcher.yml
  kafka: !include system/kafka-all-test.yml
  keycloak: !include system/keycloak.yml
  keycloak-container: !include system/keycloak-container-test.yml
  message-bus: !include system/message-bus-test.yml
  onfido-adapter: !include system/onfido-adapter.yml
  onfido-adapter-relay: !include system/onfido-adapter-relay.yml
  onfido-adapter-server: !include system/onfido-adapter-server.yml
  onfido-simulator-server: !include system/onfido-simulator-server.yml
  parties: !include test-api-scenarios/party-test.yml
  parties-relay: !include system/party-relay.yml
  payee-checks: !include system/payee-check-test.yml
  payments: !include system/payment.yml
  payments-dispatcher: !include system/payment-dispatcher.yml
  policies: !include system/policy-test.yml
  scenario-policies: !include test-api-scenarios/policy-test.yml
  server: !include test-api-scenarios/server-test.yml
  telemetry: !include system/telemetry.yml
  transactions: !include system/transaction.yml
  transactions-dispatcher: !include system/transaction-dispatcher.yml
  uk-companies-house-adapter: !include system/uk-companies-house-adapter.yml
  uk-companies-house-simulator-server: !include system/uk-companies-house-simulator-server.yml
