syntax = "proto2";

package com.repldriven.queenswood.schemas.payments;

import "record_metadata_options.proto";

option java_outer_classname = "InboundPaymentProto";

enum InboundPaymentStatus {
  INBOUND_PAYMENT_STATUS_UNKNOWN = 0;
  INBOUND_PAYMENT_STATUS_SETTLED = 1;
  INBOUND_PAYMENT_STATUS_SUSPENDED = 2;
  INBOUND_PAYMENT_STATUS_HELD = 3;
  INBOUND_PAYMENT_STATUS_RETURNED = 4;
  INBOUND_PAYMENT_STATUS_ADMITTED = 5;
}

message InboundPayment {
  option (com.apple.foundationdb.record.record).usage = RECORD;
  required string payment_id = 1 [(com.apple.foundationdb.record.field).primary_key = true];
  required string scheme_transaction_id = 2;
  required string end_to_end_id = 3;
  required string scheme = 4;
  optional string creditor_account_id = 5;
  required string currency = 6;
  required int64 amount = 7;
  optional string transaction_id = 8;
  optional string debtor_name = 9;
  optional string reference = 10;
  required int64 created_at = 11;
  required int64 updated_at = 12;
  required string bank_id = 13;
  required int64 business_day = 14;
  required InboundPaymentStatus payment_status = 15;
  optional string suspense_reason_code = 16;
  optional string suspense_reason = 17;
}
