system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  idv-provider: !include system/idv-provider.yml
  idv: !include idv/idv-test.yml
  policies: !include system/policy-test.yml
