syntax = "proto2";

package com.repldriven.queenswood.schemas.cash_account_products;

import "record_metadata_options.proto";
import "schemas/account-product-type/account-product-type.proto";
import "schemas/cash-account-products/types.proto";

option java_outer_classname = "CashAccountProductTemplateProto";

// A platform template a cash account product is created from.
message CashAccountProductTemplate {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string template_id = 1 [(com.apple.foundationdb.record.field).primary_key = true];

  required string name = 2;
  required com.repldriven.queenswood.schemas.account_product_type.AccountProductType product_type = 3;
  required IsoCashAccountType iso_cash_account_type = 4;
  required BalanceSheetSide balance_sheet_side = 5;
  required bool internal = 6;
  repeated string allowed_currencies = 7; // ISO 4217
  repeated BalanceProduct balance_products = 8;
  repeated PaymentAddressScheme allowed_payment_address_schemes = 9;

  required int64 created_at = 101;
  optional int64 updated_at = 103;
}
