system:
  kafka:
    schemas: !system/component
      system/component-kind: avro/serde
      schemas:
        command: schemas/command/command-envelope.avsc.json
        command-response: schemas/command/command-response.avsc.json
        event: schemas/event/event-envelope.avsc.json
    producers: !system/component
      system/component-kind: kafka/producers
      banks-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-banks-command-response
          acks: all
      memberships-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-memberships-command-response
          acks: all
      parties-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-parties-command-response
          acks: all
      cash-accounts-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-cash-accounts-command-response
          acks: all
      idv-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-idv-command
          acks: all
      banks-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-banks-command-dlq
          acks: all
      memberships-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-memberships-command-dlq
          acks: all
      parties-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-parties-command-dlq
          acks: all
      cash-accounts-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-cash-accounts-command-dlq
          acks: all
      cash-accounts-event-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-cash-accounts-event-dlq
          acks: all
      idvs-event-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-idvs-event-dlq
          acks: all
      parties-event-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-parties-event-dlq
          acks: all
    consumers: !system/component
      system/component-kind: kafka/consumers
      banks-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-banks-command]
        dead-letter-producer: !system/local-ref producers.banks-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: bank-service-banks-command
      memberships-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-memberships-command]
        dead-letter-producer: !system/local-ref producers.memberships-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: membership-service-memberships-command
      parties-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-parties-command]
        dead-letter-producer: !system/local-ref producers.parties-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: party-service-parties-command
      cash-accounts-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-cash-accounts-command]
        dead-letter-producer: !system/local-ref producers.cash-accounts-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: cash-account-service-cash-accounts-command
      idv-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        topics: [topic-idv-event]
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: idv-service-idv-event
      cash-accounts-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        topics: [topic-cash-accounts-event]
        dead-letter-producer: !system/local-ref producers.cash-accounts-event-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: cash-account-service-cash-accounts-event
      parties-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        topics: [topic-parties-event]
        dead-letter-producer: !system/local-ref producers.parties-event-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: idv-service-parties-event
      idvs-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        topics: [topic-idvs-event]
        dead-letter-producer: !system/local-ref producers.idvs-event-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: party-service-idvs-event
    message-bus-producers: !system/component
      system/component-kind: kafka/message-bus-producers
      banks-command-response:
        producer: !system/local-ref producers.banks-command-response
      memberships-command-response:
        producer: !system/local-ref producers.memberships-command-response
      parties-command-response:
        producer: !system/local-ref producers.parties-command-response
      cash-accounts-command-response:
        producer: !system/local-ref producers.cash-accounts-command-response
      idv-command:
        producer: !system/local-ref producers.idv-command
    message-bus-consumers: !system/component
      system/component-kind: kafka/message-bus-consumers
      banks-command:
        consumer: !system/local-ref consumers.banks-command
        timeout: 500
      memberships-command:
        consumer: !system/local-ref consumers.memberships-command
        timeout: 500
      parties-command:
        consumer: !system/local-ref consumers.parties-command
        timeout: 500
      cash-accounts-command:
        consumer: !system/local-ref consumers.cash-accounts-command
        timeout: 500
      idv-event:
        consumer: !system/local-ref consumers.idv-event
        timeout: 500
      cash-accounts-event:
        consumer: !system/local-ref consumers.cash-accounts-event
        timeout: 500
      parties-event:
        consumer: !system/local-ref consumers.parties-event
        timeout: 500
      idvs-event:
        consumer: !system/local-ref consumers.idvs-event
        timeout: 500
  message-bus: !include system/message-bus.yml
  fdb: !include system/fdb.yml
  avro: !include system/avro.yml
  keycloak: !include system/keycloak.yml
  banks: !include system/bank.yml
  memberships: !include system/membership.yml
  parties: !include system/party.yml
  cash-accounts: !include system/cash-account.yml
  idv: !include system/idv.yml
  telemetry: !include system/telemetry.yml
