system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  message-bus: !include clearbank-relay/message-bus-test.yml
  relay-handler:
    handler: !system/component
      system/component-kind: changelog-relay/envelope-handler
      bus: !system/ref message-bus.bus
      store-name: clearbank-outbox
      event-channel: !keyword schemes-payments-event
