syntax = "proto2";

package com.repldriven.queenswood.schemas.members;

import "record_metadata_options.proto";
import "schemas/actor/actor.proto";

option java_outer_classname = "MemberProto";

enum Role {
  ROLE_UNKNOWN = 0;
  ROLE_OWNER = 1;
  ROLE_ADMIN = 2;
  ROLE_DEVELOPER = 3;
  ROLE_VIEWER = 4;
}

enum MemberStatus {
  MEMBER_STATUS_UNKNOWN = 0;
  MEMBER_STATUS_ACTIVE = 1;
  MEMBER_STATUS_REMOVED = 2;
  MEMBER_STATUS_LEFT = 3;
}

// A user's role in a bank.
message Member {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string bank_id = 1;
  required string member_id = 2; // mem.<uuidv7>

  required MemberStatus status = 3;
  required Role role = 4;
  required string user_id = 5;
  optional string invitation_id = 6;
  optional string removed_reason = 7;

  optional int64 removed_at = 51;
  optional com.repldriven.queenswood.schemas.actor.Actor removed_by = 52;
  optional int64 left_at = 53;
  optional com.repldriven.queenswood.schemas.actor.Actor left_by = 54;

  required int64 created_at = 101;
  required com.repldriven.queenswood.schemas.actor.Actor created_by = 102;
  optional int64 updated_at = 103;
}
