syntax = "proto2";

package com.repldriven.queenswood.schema;

import "record_metadata_options.proto";

import "schemas/balance/account-balance.proto";
import "schemas/cash-account-migration/cash-account-migration.proto";
import "schemas/cash-account-migration/cash-account-migration-account-run.proto";
import "schemas/cash-account-migration/cash-account-migration-run.proto";
import "schemas/cash-account-product/cash-account-product-template.proto";
import "schemas/cash-account-product/cash-account-product.proto";
import "schemas/cash-account/cash-account.proto";
import "schemas/company/company.proto";
import "schemas/email/email-delivery.proto";
import "schemas/idempotency/idempotency.proto";
import "schemas/idv/idv.proto";
import "schemas/idv/idv-session.proto";
import "schemas/interest/interest-account-run.proto";
import "schemas/interest/interest-run.proto";
import "schemas/ledger-account/ledger-account.proto";
import "schemas/scheduler/scheduler-job.proto";
import "schemas/scheduler/scheduler-run.proto";
import "schemas/member/invitation.proto";
import "schemas/member/member.proto";
import "schemas/member/member-role-change.proto";
import "schemas/modulr/modulr-outbound-intent.proto";
import "schemas/modulr/modulr-outbox-event.proto";
import "schemas/form3/form3-outbound-intent.proto";
import "schemas/form3/form3-outbox-event.proto";
import "schemas/bank/bank.proto";
import "schemas/onfido/onfido-outbound-intent.proto";
import "schemas/onfido/onfido-outbox-event.proto";
import "schemas/circuit-breaker/circuit-breaker.proto";
import "schemas/zyphe/zyphe-outbound-intent.proto";
import "schemas/zyphe/zyphe-outbox-event.proto";
import "schemas/clearbank/clearbank-outbound-intent.proto";
import "schemas/clearbank/clearbank-outbox-event.proto";
import "schemas/party/party.proto";
import "schemas/payee-check/payee-check.proto";
import "schemas/payment/inbound-payment.proto";
import "schemas/payment/internal-payment.proto";
import "schemas/payment/outbound-payment.proto";
import "schemas/payment/payment-provider-transfer.proto";
import "schemas/policy/policy.proto";
import "schemas/policy/policy-binding.proto";
import "schemas/reward/account-reward.proto";
import "schemas/transaction/transaction.proto";
import "schemas/transaction/transaction-leg.proto";
import "schemas/user/user.proto";
import "schemas/webhook/webhook-delivery.proto";
import "schemas/webhook/webhook-delivery-attempt.proto";
import "schemas/webhook/webhook-endpoint.proto";
import "schemas/webhook/webhook-notification.proto";

option java_outer_classname = "SchemaProto";

option (com.apple.foundationdb.record.schema).store_record_versions = true;
option (com.apple.foundationdb.record.schema).split_long_records = true;

// The record types the Record Layer stores.
message RecordTypeUnion {
  optional com.repldriven.queenswood.schema.cash_account.CashAccount _CashAccount = 1;
  reserved 2;
  optional com.repldriven.queenswood.schema.bank.Bank _Bank = 3;
  reserved 4;
  optional com.repldriven.queenswood.schema.party.Party _Party = 6;
  optional com.repldriven.queenswood.schema.idv.Idv _Idv = 7;
  reserved 9;
  optional com.repldriven.queenswood.schema.cash_account_product.CashAccountProduct _CashAccountProduct = 10;
  optional com.repldriven.queenswood.schema.balance.AccountBalance _AccountBalance = 11;
  optional com.repldriven.queenswood.schema.transaction.Transaction _Transaction = 12;
  optional com.repldriven.queenswood.schema.transaction.TransactionLeg _TransactionLeg = 13;
  optional com.repldriven.queenswood.schema.payment.InternalPayment _InternalPayment = 14;
  optional com.repldriven.queenswood.schema.payment.InboundPayment _InboundPayment = 15;
  optional com.repldriven.queenswood.schema.payment.OutboundPayment _OutboundPayment = 16;
  reserved 17;
  optional com.repldriven.queenswood.schema.payee_check.PayeeCheck _PayeeCheck = 18;
  optional com.repldriven.queenswood.schema.policy.Policy _Policy = 19;
  optional com.repldriven.queenswood.schema.policy.PolicyBinding _PolicyBinding = 20;
  optional com.repldriven.queenswood.schema.idempotency.Idempotency _Idempotency = 21;
  optional com.repldriven.queenswood.schema.user.User _User = 22;
  optional com.repldriven.queenswood.schema.member.Member _Member = 23;
  optional com.repldriven.queenswood.schema.company.Company _Company = 25;
  optional com.repldriven.queenswood.schema.ledger_account.LedgerAccount _LedgerAccount = 26;
  optional com.repldriven.queenswood.schema.interest.InterestRun _InterestRun = 27;
  optional com.repldriven.queenswood.schema.cash_account_product.CashAccountProductTemplate _CashAccountProductTemplate = 28;
  optional com.repldriven.queenswood.schema.scheduler.SchedulerJob _SchedulerJob = 29;
  optional com.repldriven.queenswood.schema.scheduler.SchedulerRun _SchedulerRun = 30;
  optional com.repldriven.queenswood.schema.clearbank.ClearbankOutboxEvent _ClearbankOutboxEvent = 31;
  optional com.repldriven.queenswood.schema.clearbank.ClearbankOutboundIntent _ClearbankOutboundIntent = 32;
  optional com.repldriven.queenswood.schema.onfido.OnfidoOutboxEvent _OnfidoOutboxEvent = 33;
  optional com.repldriven.queenswood.schema.onfido.OnfidoOutboundIntent _OnfidoOutboundIntent = 34;
  optional com.repldriven.queenswood.schema.interest.InterestAccountRun _InterestAccountRun = 35;
  optional com.repldriven.queenswood.schema.cash_account_migration.CashAccountMigration _CashAccountMigration = 36;
  optional com.repldriven.queenswood.schema.cash_account_migration.CashAccountMigrationRun _CashAccountMigrationRun = 37;
  optional com.repldriven.queenswood.schema.cash_account_migration.CashAccountMigrationAccountRun _CashAccountMigrationAccountRun = 38;
  optional com.repldriven.queenswood.schema.webhook.WebhookEndpoint _WebhookEndpoint = 39;
  optional com.repldriven.queenswood.schema.webhook.WebhookNotification _WebhookNotification = 40;
  optional com.repldriven.queenswood.schema.webhook.WebhookDelivery _WebhookDelivery = 41;
  optional com.repldriven.queenswood.schema.webhook.WebhookDeliveryAttempt _WebhookDeliveryAttempt = 42;
  optional com.repldriven.queenswood.schema.member.Invitation _Invitation = 43;
  optional com.repldriven.queenswood.schema.member.MemberRoleChange _MemberRoleChange = 44;
  optional com.repldriven.queenswood.schema.email.EmailDelivery _EmailDelivery = 45;
  optional com.repldriven.queenswood.schema.reward.AccountReward _AccountReward = 46;
  optional com.repldriven.queenswood.schema.zyphe.ZypheOutboxEvent _ZypheOutboxEvent = 47;
  optional com.repldriven.queenswood.schema.zyphe.ZypheOutboundIntent _ZypheOutboundIntent = 48;
  optional com.repldriven.queenswood.schema.idv.IdvSession _IdvSession = 49;
  optional com.repldriven.queenswood.schema.modulr.ModulrOutboxEvent _ModulrOutboxEvent = 50;
  optional com.repldriven.queenswood.schema.modulr.ModulrOutboundIntent _ModulrOutboundIntent = 51;
  optional com.repldriven.queenswood.schema.payment.PaymentProviderTransfer _PaymentProviderTransfer = 52;
  optional com.repldriven.queenswood.schema.form3.Form3OutboxEvent _Form3OutboxEvent = 53;
  optional com.repldriven.queenswood.schema.form3.Form3OutboundIntent _Form3OutboundIntent = 54;
  optional com.repldriven.queenswood.schema.circuit_breaker.CircuitBreaker _CircuitBreaker = 55;
}
