system:
  kafka:
    schemas: !system/component
      system/component-kind: avro/serde
      schemas:
        command: schemas/command/command-envelope.avsc.json
        command-response: schemas/command/command-response.avsc.json
        event: schemas/event/event-envelope.avsc.json
    producers: !system/component
      system/component-kind: kafka/producers
      payments-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-payments-command-response
          acks: all
      schemes-payment-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-schemes-payment-command
          acks: all
      transactions-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-transactions-command-response
          acks: all
      interest-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-interest-command-response
          acks: all
      payee-checks-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-payee-checks-command-response
          acks: all
      payments-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-payments-command-dlq
          acks: all
      schemes-payments-event-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-schemes-payments-event-dlq
          acks: all
      transactions-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-transactions-command-dlq
          acks: all
      interest-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-interest-command-dlq
          acks: all
      payee-checks-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-payee-checks-command-dlq
          acks: all
    consumers: !system/component
      system/component-kind: kafka/consumers
      payments-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-payments-command]
        dead-letter-producer: !system/local-ref producers.payments-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: payment-service-payments-command
      schemes-payments-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        topics: [topic-schemes-payments-event]
        dead-letter-producer: !system/local-ref producers.schemes-payments-event-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: payment-service-schemes-payments-event
      transactions-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-transactions-command]
        dead-letter-producer: !system/local-ref producers.transactions-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: transaction-service-transactions-command
      interest-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-interest-command]
        dead-letter-producer: !system/local-ref producers.interest-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: interest-service-interest-command
      payee-checks-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-payee-checks-command]
        dead-letter-producer: !system/local-ref producers.payee-checks-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: payee-check-service-payee-checks-command
    message-bus-producers: !system/component
      system/component-kind: kafka/message-bus-producers
      payments-command-response:
        producer: !system/local-ref producers.payments-command-response
      schemes-payment-command:
        producer: !system/local-ref producers.schemes-payment-command
      transactions-command-response:
        producer: !system/local-ref producers.transactions-command-response
      interest-command-response:
        producer: !system/local-ref producers.interest-command-response
      payee-checks-command-response:
        producer: !system/local-ref producers.payee-checks-command-response
    message-bus-consumers: !system/component
      system/component-kind: kafka/message-bus-consumers
      payments-command:
        consumer: !system/local-ref consumers.payments-command
        timeout: 500
      schemes-payments-event:
        consumer: !system/local-ref consumers.schemes-payments-event
        timeout: 500
      transactions-command:
        consumer: !system/local-ref consumers.transactions-command
        timeout: 500
      interest-command:
        consumer: !system/local-ref consumers.interest-command
        timeout: 500
      payee-checks-command:
        consumer: !system/local-ref consumers.payee-checks-command
        timeout: 500
  message-bus: !include system/message-bus.yml
  fdb: !include system/fdb.yml
  avro: !include system/avro.yml
  payments: !include system/payment.yml
  transactions: !include system/transaction.yml
  interest: !include system/interest.yml
  payee-checks: !include system/payee-check.yml
  telemetry: !include system/telemetry.yml
